export enum ENVEnum {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',

  DATABASE_URL = 'DATABASE_URL',

  JWT_SECRET = 'JWT_SECRET',
  ACCESS_TOKEN_EXPIRES_IN = 'ACCESS_TOKEN_EXPIRES_IN',

  SUPABASE_URL = 'SUPABASE_URL',
  SUPABASE_KEY = 'SUPABASE_KEY',
}

export enum NODE_ENV {
  PRODUCTION = 'production',
  DEVELOPMENT = 'development',
  TEST = 'test',
}
