name: CD Pipeline

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["CI Check"]
    types:
      - completed

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-inventory-api:latest

  deploy:
    name: Trigger Render Deployment
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Call Render Deploy Hook for Docker Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
      - name: Confirm Deployment Triggered
        run: echo "Render deployment triggered successfully."